services:
  - type: web
    name: takmine-movie-app
    # runtime: php の行を削除します
    plan: free
    buildCommand: 'echo "No build step"'
    startCommand: 'php -S 0.0.0.0:10000 -t .'
    envVars:
      - key: RENDER
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: movie-db
          property: connectionString # ここを修正しました！

databases:
  - name: movie-db
    plan: free